In [1]:
#!pip install --upgrade --force-reinstall scipy scikit-learn numpy==1.26.4
!pip install -r requirements.txt

  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/ab/a7/0ddaf514ce8a8714f6ed243a2b391b41dbb65251affe21ee3077ec45ea9a/scipy-1.15.3-cp311-cp311-win_amd64.whl.metadata
  Using cached scipy-1.15.3-cp311-cp311-win_amd64.whl.metadata (60 kB)
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/a1/a6/c5b78606743a1f28eae8f11973de6613a5ee87366796583fb74c67d54939/scikit_learn-1.6.1-cp311-cp311-win_amd64.whl.metadata
  Using cached scikit_learn-1.6.1-cp311-cp311-win_amd64.whl.metadata (15 kB)
  Obtaining dependency information for numpy==1.26.4 from https://files.pythonhosted.org/packages/3f/6b/5610004206cf7f8e7ad91c5a85a8c71b2f2f8051a0c0c4d5916b76d6cbb2/numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata
  Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
  Obtaining dependency information for joblib>=1.2.0 from https://files.pythonhosted.org/packages/7d/4f/1195bbac8e0c2acc5f740661631d8d750dc38d4a3

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\kacha\\anaconda3\\Lib\\site-packages\\~umpy.libs\\libscipy_openblas64_-caad452230ae4ddb57899b8b3a33c55c.dll'
Consider using the `--user` option or check the permissions.



In [2]:
import re
import string
from sklearn.metrics import precision_score, recall_score, confusion_matrix, accuracy_score

In [3]:
# Sample sentences for testing
sample_sentences = [
    "Hello! How are you doing today?",
    "This is a simple tokenizer test-case.",
    "Let's see how well it performs on punctuation and numbers like 123!",
    "Tokenizer should remove punctuations, handle spaces and return words properly.",
]


In [4]:
def basic_tokenizer(text):
    # Convert to lowercase
    text = text.lower()
    
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    
    # Split into words using regex to avoid empty tokens
    tokens = re.findall(r'\b\w+\b', text)
    
    return tokens


In [5]:
# Test tokenizer
for i, sentence in enumerate(sample_sentences):
    print(f"Sentence {i+1}: {sentence}")
    print("Tokens:", basic_tokenizer(sentence))
    print("-" * 50)

Sentence 1: Hello! How are you doing today?
Tokens: ['hello', 'how', 'are', 'you', 'doing', 'today']
--------------------------------------------------
Sentence 2: This is a simple tokenizer test-case.
Tokens: ['this', 'is', 'a', 'simple', 'tokenizer', 'testcase']
--------------------------------------------------
Sentence 3: Let's see how well it performs on punctuation and numbers like 123!
Tokens: ['lets', 'see', 'how', 'well', 'it', 'performs', 'on', 'punctuation', 'and', 'numbers', 'like', '123']
--------------------------------------------------
Sentence 4: Tokenizer should remove punctuations, handle spaces and return words properly.
Tokens: ['tokenizer', 'should', 'remove', 'punctuations', 'handle', 'spaces', 'and', 'return', 'words', 'properly']
--------------------------------------------------


In [6]:
# we simulate token comparison for evaluation.
y_true = [
    ['hello', 'how', 'are', 'you', 'doing', 'today'],
    ['this', 'is', 'a', 'simple', 'tokenizer', 'testcase'],
]

y_pred = [
    basic_tokenizer(sample_sentences[0]),
    basic_tokenizer(sample_sentences[1]),
]


In [7]:
# Flatten and compare
y_true_flat = [item for sublist in y_true for item in sublist]
y_pred_flat = [item for sublist in y_pred for item in sublist]

In [8]:
# Make lengths equal for comparison (pad shorter list)
min_len = min(len(y_true_flat), len(y_pred_flat))
y_true_flat = y_true_flat[:min_len]
y_pred_flat = y_pred_flat[:min_len]

In [9]:
# Accuracy and Evaluation
print("\n--- Evaluation Metrics ---")
print("Confusion Matrix:", confusion_matrix(y_true_flat, y_pred_flat, labels=list(set(y_true_flat))))
print("Precision:", precision_score(y_true_flat, y_pred_flat, average='micro'))
print("Recall:", recall_score(y_true_flat, y_pred_flat, average='micro'))
print("Accuracy:", accuracy_score(y_true_flat, y_pred_flat))


--- Evaluation Metrics ---
Confusion Matrix: [[1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]]
Precision: 1.0
Recall: 1.0
Accuracy: 1.0
